sudo: false # faster builds

language: java

before_install:
  - chmod +x gradlew
  # Amazon JDK -- https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source install-jdk.sh --url https://d3pxv6yz143wms.cloudfront.net/11.0.3.7.1/amazon-corretto-11.0.3.7.1-linux-x64.tar.gz
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version

script:
  - ./gradlew projects clean build jacocoTestReport --no-daemon --refresh-dependencies

after_success:
  - bash <(curl -s https://codecov.io/bash)
